# Generated by Django 2.1.2 on 2018-10-17 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=100)),
                ('rut', models.CharField(max_length=10)),
                ('nombreCompleto', models.CharField(max_length=200)),
                ('f_nacimiento', models.DateTimeField()),
                ('fono', models.CharField(max_length=9)),
                ('region', models.CharField(max_length=30)),
                ('comuna', models.CharField(max_length=30)),
                ('tipoVivienda', models.CharField(max_length=30)),
            ],
        ),
    ]
