# Generated by Django 2.1.2 on 2018-10-30 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('misPerris', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mascota',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto', models.ImageField(upload_to='')),
                ('nombre', models.CharField(max_length=100)),
                ('raza', models.CharField(max_length=100)),
                ('descripcion', models.CharField(max_length=200)),
                ('estado', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='usuario',
            name='f_nacimiento',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='fono',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='rut',
            field=models.EmailField(max_length=254),
        ),
    ]
