# Generated by Django 2.1.2 on 2018-10-30 17:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('misPerris', '0002_auto_20181030_1421'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mascota',
            name='foto',
        ),
    ]
